name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ssebi001/portofolio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest tag from Docker Hub
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/tags?page_size=1" | jq -r '.results[0].name')
          echo "Latest tag: $LATEST_TAG"
          
          IFS='.' read -r MAJOR MINOR <<< "$LATEST_TAG"
          NEW_MINOR=$((MINOR + 1))
          NEW_TAG="$MAJOR.$NEW_MINOR"
          echo "New tag: $NEW_TAG"
          
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |          
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.new_tag }} .

      - name: Push image to Docker Hub (version tag)
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.new_tag }}
