name: Deploy to Live

on:
  push:
    branches:
      - live
    paths:
      - 'run.yml'

jobs:
  deploy:
    name: Deploy to Live
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd websites/Portofolio
            git pull origin live
            docker-compose -f run.yml up -d
