name: Deploy to Live

on:
  push:
    branches:
      - live
    paths:
      - 'run.yml'

jobs:
  deploy:
    name: Deploy to Live
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and deploy
        run: |
          ssh ${{ secrets.SSH_HOST }} << 'EOF'
            cd websites/Portofolio
            git pull origin live
            docker compose -f run.yml up -d
          EOF
